import asyncio
from typing import Dict, Any
from domain.contracts.logging import logger
from agents.shared.triage_a2a_agent import TriageA2AAgent
from agents.shared.application_a2a_agent import ApplicationA2AAgent
from agents.shared.infrastructure_a2a_agent import InfrastructureA2AAgent

class A2AGateway:
    def __init__(self):
        self.agents = {
            "triage": TriageA2AAgent(),
            "application": ApplicationA2AAgent(),
            "infrastructure": InfrastructureA2AAgent()
        }
        self.cards = {name: agent.card for name, agent in self.agents.items()}

    async def process_incident(self, incident_data: Dict[str, Any]) -> Dict[str, Any]:
        triage_result = await self.agents["triage"].send_request(
            self.agents["triage"].card.endpoint,
            {"method": "analyze", "params": {"evidence_summary": incident_data.get("summary", "")}}
        )
        incident_type = triage_result.get("result", {}).get("finding_type", "").replace("triage_", "")
        analysis_results = []
        if incident_type in ["application", "infrastructure"]:
            app_task = self.agents["application"].send_request(
                self.agents["application"].card.endpoint,
                {"method": "analyze", "params": {"evidence_summary": incident_data.get("summary", "")}}
            )
            infra_task = self.agents["infrastructure"].send_request(
                self.agents["infrastructure"].card.endpoint,
                {"method": "analyze", "params": {"evidence_summary": incident_data.get("summary", "")}}
            )
            analysis_results = await asyncio.gather(app_task, infra_task)
        return {
            "triage": triage_result,
            "analysis": analysis_results,
            "final_plan": "Plan generated by gateway"
        }