(() => {
  const baseRenderDetail = renderDetail;

  function approvalPanel() {
    const lifecycle = S.detail?.lifecycle || {};
    const approval = lifecycle.approval || null;
    const decision = lifecycle.decision || {};
    if (!approval) {
      return `<div class="approval-card neutral">
        <div class="approval-card-head"><div><span class="section-kicker">Human gate</span><h4>No approval request</h4></div>${pill('not requested')}</div>
        <p>No durable approval is currently associated with this incident. Approval actions appear only after the workflow creates a governed request.</p>
      </div>`;
    }

    const status = lower(approval.status || 'unknown');
    const meta = approval.metadata || {};
    const risk = approval.risk_level || decision.risk_level || decision.risk || 'unknown';
    const pending = status === 'pending';
    const approved = status === 'approved';
    const consumed = status === 'consumed';
    const reason = meta.rejection_reason || '';
    const actor = meta.approved_by || meta.rejected_by || approval.approver || '—';
    const when = approval.approved_at || approval.rejected_at || approval.created_at;
    const binding = meta.binding_complete === true || lower(meta.binding_complete) === 'true';

    let controls = '';
    if (pending) {
      controls = `<div class="approval-controls">
        <textarea id="rejectReason" maxlength="1000" placeholder="Rejection reason (required for Reject)"></textarea>
        <div class="approval-buttons">
          <button class="approval-btn reject" onclick="rejectCurrentApproval()">Reject</button>
          <button class="approval-btn approve" onclick="approveCurrentApproval()">Approve</button>
        </div>
      </div>`;
    } else if (approved) {
      controls = `<div class="execution-controls">
        <div class="execution-ready"><span class="dot green"></span><div><strong>Approval granted — execution not started</strong><small>The workflow is paused at the one-time authorization boundary. Resume validates the binding, issues a short-lived signed capability, consumes this approval exactly once, executes through the governed MCP boundary, then verifies recovery.</small></div></div>
        <button id="resumeExecutionBtn" class="approval-btn execute" onclick="resumeCurrentWorkflow()" ${binding ? '' : 'disabled'}>Resume & Execute</button>
        ${binding ? '' : '<p class="approval-warning">Execution binding is incomplete; resume is intentionally disabled.</p>'}
      </div>`;
    } else if (consumed) {
      controls = `<div class="execution-consumed"><strong>One-time approval consumed</strong><p>This authorization cannot be reused. Any new execution attempt requires a new governed approval generated by a fresh workflow decision.</p></div>`;
    }

    return `<div class="approval-card ${pending ? 'pending' : status}">
      <div class="approval-card-head">
        <div><span class="section-kicker">Governed authorization</span><h4>${esc(approval.action || decision.action || 'Proposed remediation')}</h4></div>
        ${pill(status)}
      </div>
      <div class="approval-facts">
        <div><label>Approval ID</label><strong>${esc(String(approval.approval_id || '').slice(0, 12) || '—')}</strong></div>
        <div><label>Risk</label><strong>${esc(risk)}</strong></div>
        <div><label>Binding</label><strong>${binding ? 'complete' : 'incomplete'}</strong></div>
        <div><label>Environment</label><strong>${esc(meta.environment || '—')}</strong></div>
        <div><label>Tool</label><strong>${esc(meta.tool_name || '—')}</strong></div>
        <div><label>Action</label><strong>${esc(approval.action || decision.action || '—')}</strong></div>
        <div><label>Target</label><strong>${esc(meta.target || '—')}</strong></div>
        <div><label>Runbook</label><strong>${esc([meta.runbook_id, meta.runbook_version].filter(Boolean).join(' @ ') || '—')}</strong></div>
      </div>
      <p class="approval-note">Approval authorizes only the bound execution intent. It does not execute by itself. The signed capability is created only when the workflow resumes and is never displayed in the browser.</p>
      ${controls}
      ${!pending && !approved && !consumed ? `<div class="approval-result">
        <div><label>Actor</label><strong>${esc(actor)}</strong></div>
        <div><label>Time</label><strong>${fmtDate(when)}</strong></div>
        ${reason ? `<div class="approval-reason"><label>Rejection reason</label><p>${esc(reason)}</p></div>` : ''}
      </div>` : ''}
    </div>`;
  }

  async function refreshIncidentDecision() {
    const id = S.selected;
    if (!id) return;
    await selectIncident(id);
    renderDetail('decision');
  }

  window.approveCurrentApproval = async function approveCurrentApproval() {
    const approval = S.detail?.lifecycle?.approval;
    if (!approval?.approval_id || lower(approval.status) !== 'pending') return;
    const risk = lower(approval.risk_level);
    const first = window.confirm(`Approve governed action "${approval.action}"?\n\nThis grants authorization but does NOT execute it yet.`);
    if (!first) return;
    if (risk === 'high' && !window.confirm('HIGH-RISK approval: confirm that you reviewed target, tool, evidence, runbook and blast radius.')) return;
    try {
      await api(`/api/v1/approvals/${encodeURIComponent(approval.approval_id)}/approve`, {method: 'POST'});
      toast('Approval granted. Workflow remains paused until Resume & Execute.');
      await refreshIncidentDecision();
    } catch (error) {
      showError(error.message);
      toast('Approval failed');
    }
  };

  window.rejectCurrentApproval = async function rejectCurrentApproval() {
    const approval = S.detail?.lifecycle?.approval;
    if (!approval?.approval_id || lower(approval.status) !== 'pending') return;
    const input = document.querySelector('#rejectReason');
    const reason = String(input?.value || '').trim();
    if (!reason) {
      toast('Rejection reason is required');
      input?.focus();
      return;
    }
    if (!window.confirm(`Reject governed action "${approval.action}"?`)) return;
    try {
      await api(`/api/v1/approvals/${encodeURIComponent(approval.approval_id)}/reject`, {
        method: 'POST',
        headers: {'Content-Type': 'application/json'},
        body: JSON.stringify({reason})
      });
      toast('Approval rejected and audited');
      await refreshIncidentDecision();
    } catch (error) {
      showError(error.message);
      toast('Rejection failed');
    }
  };

  window.resumeCurrentWorkflow = async function resumeCurrentWorkflow() {
    const lifecycle = S.detail?.lifecycle || {};
    const approval = lifecycle.approval;
    const id = S.selected;
    if (!id || !approval?.approval_id || lower(approval.status) !== 'approved') return;
    const meta = approval.metadata || {};
    const binding = meta.binding_complete === true || lower(meta.binding_complete) === 'true';
    if (!binding) {
      toast('Execution binding is incomplete');
      return;
    }
    const summary = [meta.tool_name, approval.action, meta.target].filter(Boolean).join(' → ');
    if (!window.confirm(`Resume this approved workflow and execute the bound action?\n\n${summary}\n\nThe approval will be consumed exactly once when execution begins.`)) return;
    if (lower(approval.risk_level) === 'high' && !window.confirm('HIGH-RISK execution: confirm final operator intent to consume the approval and execute now.')) return;

    const button = document.querySelector('#resumeExecutionBtn');
    if (button) {
      button.disabled = true;
      button.textContent = 'Executing…';
    }
    showError();
    try {
      const result = await api(`/api/v1/workflow/e2e/${encodeURIComponent(id)}/resume`, {method: 'POST'});
      const verification = result.verification_result?.status || 'not recorded';
      toast(`Execution completed · verification ${verification}`);
      await loadAll();
      await refreshIncidentDecision();
    } catch (error) {
      showError(`Resume/execute failed: ${error.message}`);
      toast('Execution did not complete');
      await refreshIncidentDecision();
    }
  };

  renderDetail = function enhancedRenderDetail(tab = 'overview') {
    baseRenderDetail(tab);
    if (tab !== 'decision') return;
    const pane = document.querySelector('#detailPane');
    if (!pane) return;
    const existing = pane.innerHTML;
    pane.innerHTML = `${approvalPanel()}${existing}`;
  };
})();
