(() => {
  const baseSelectIncident = selectIncident;
  const baseRenderDetail = renderDetail;
  const baseLoadAll = loadAll;

  function approvalPanel() {
    const lifecycle = S.detail?.lifecycle || {};
    const approval = lifecycle.approval || null;
    const decision = lifecycle.decision || {};
    if (!approval) {
      return `<div class="approval-card neutral">
        <div class="approval-card-head"><div><span class="section-kicker">Human gate</span><h4>No approval request</h4></div>${pill('not requested')}</div>
        <p>No durable approval is currently associated with this incident. Approval actions appear only after the workflow creates a governed request.</p>
      </div>`;
    }

    const status = lower(approval.status || 'unknown');
    const meta = approval.metadata || {};
    const risk = approval.risk_level || decision.risk_level || decision.risk || 'unknown';
    const pending = status === 'pending';
    const approved = status === 'approved';
    const consumed = status === 'consumed';
    const reason = meta.rejection_reason || '';
    const actor = meta.approved_by || meta.rejected_by || approval.approver || '—';
    const when = approval.approved_at || approval.rejected_at || approval.created_at;
    const binding = meta.binding_complete === true || lower(meta.binding_complete) === 'true';

    let controls = '';
    if (pending) {
      controls = `<div class="approval-controls">
        <textarea id="rejectReason" maxlength="1000" placeholder="Rejection reason (required for Reject)"></textarea>
        <div class="approval-buttons">
          <button class="approval-btn reject" onclick="rejectCurrentApproval()">Reject</button>
          <button class="approval-btn approve" onclick="approveCurrentApproval()">Approve</button>
        </div>
      </div>`;
    } else if (approved) {
      controls = `<div class="execution-controls">
        <div class="execution-ready"><span class="dot green"></span><div><strong>Approval granted — execution not started</strong><small>The workflow is paused at the one-time authorization boundary. Resume validates the binding, issues a short-lived signed capability, consumes this approval exactly once, executes through the governed MCP boundary, then verifies recovery.</small></div></div>
        <button id="resumeExecutionBtn" class="approval-btn execute" onclick="resumeCurrentWorkflow()" ${binding ? '' : 'disabled'}>Resume & Execute</button>
        ${binding ? '' : '<p class="approval-warning">Execution binding is incomplete; resume is intentionally disabled.</p>'}
      </div>`;
    } else if (consumed) {
      controls = `<div class="execution-consumed"><strong>One-time approval consumed</strong><p>This authorization cannot be reused. Any new execution attempt requires a new governed approval generated by a fresh workflow decision.</p></div>`;
    }

    return `<div class="approval-card ${pending ? 'pending' : status}">
      <div class="approval-card-head">
        <div><span class="section-kicker">Governed authorization</span><h4>${esc(approval.action || decision.action || 'Proposed remediation')}</h4></div>
        ${pill(status)}
      </div>
      <div class="approval-facts">
        <div><label>Approval ID</label><strong>${esc(String(approval.approval_id || '').slice(0, 12) || '—')}</strong></div>
        <div><label>Risk</label><strong>${esc(risk)}</strong></div>
        <div><label>Binding</label><strong>${binding ? 'complete' : 'incomplete'}</strong></div>
        <div><label>Environment</label><strong>${esc(meta.environment || '—')}</strong></div>
        <div><label>Tool</label><strong>${esc(meta.tool_name || '—')}</strong></div>
        <div><label>Action</label><strong>${esc(approval.action || decision.action || '—')}</strong></div>
        <div><label>Target</label><strong>${esc(meta.target || '—')}</strong></div>
        <div><label>Runbook</label><strong>${esc([meta.runbook_id, meta.runbook_version].filter(Boolean).join(' @ ') || '—')}</strong></div>
      </div>
      <p class="approval-note">Approval authorizes only the bound execution intent. It does not execute by itself. The signed capability is created only when the workflow resumes and is never displayed in the browser.</p>
      ${controls}
      ${!pending && !approved && !consumed ? `<div class="approval-result">
        <div><label>Actor</label><strong>${esc(actor)}</strong></div>
        <div><label>Time</label><strong>${fmtDate(when)}</strong></div>
        ${reason ? `<div class="approval-reason"><label>Rejection reason</label><p>${esc(reason)}</p></div>` : ''}
      </div>` : ''}
    </div>`;
  }

  function summaryBadge(label, state = 'unknown') {
    return `<span class="operator-summary-badge ${esc(state)}">${esc(label)}</span>`;
  }

  function causeBadge(summary) {
    return summaryBadge(summary.cause_confidence_fa || 'نامشخص', lower(summary.cause_confidence || 'unknown'));
  }

  function approvalBadge(status) {
    const value = lower(status);
    if (value === 'pending') return summaryBadge('نیازمند Approval', 'probable');
    if (value === 'approved') return summaryBadge('Approval تأیید شده', 'confirmed');
    if (value === 'consumed') return summaryBadge('Approval مصرف شده', 'confirmed');
    if (value === 'rejected') return summaryBadge('Approval رد شده', 'failed');
    return summaryBadge('Approval ثبت نشده', 'unknown');
  }

  function executionBadge(status) {
    const value = lower(status);
    if (value === 'success') return summaryBadge('اجرا موفق', 'confirmed');
    if (value === 'failed' || value === 'blocked') return summaryBadge('اجرا ناموفق', 'failed');
    return summaryBadge('اجرا نشده', 'unknown');
  }

  function verificationBadge(status) {
    const value = lower(status);
    if (['success', 'succeeded', 'verified'].includes(value)) return summaryBadge('Verification موفق', 'confirmed');
    if (['failed', 'failure'].includes(value)) return summaryBadge('Verification ناموفق', 'failed');
    return summaryBadge('Verification ناقص', value === 'partial' || value === 'inconclusive' ? 'probable' : 'unknown');
  }

  function memoryBadge(status) {
    const value = lower(status);
    if (value === 'persisted') return summaryBadge('در Operational Memory ذخیره شد', 'confirmed');
    if (value === 'not_persisted') return summaryBadge('در Memory ذخیره نشد', 'probable');
    return summaryBadge('Memory ثبت نشده', 'unknown');
  }

  function observedStateRows(observed = {}) {
    const rows = [];
    const svc = observed.service_status || {};
    if (observed.service) rows.push(['Service', observed.service]);
    if (observed.target) rows.push(['Host / IP', observed.target]);
    if (observed.port) rows.push(['Port', observed.port]);
    if (svc.active_state || svc.sub_state) rows.push(['Service status', [svc.active_state, svc.sub_state].filter(Boolean).join('/')]);
    if (observed.process_status?.running != null) rows.push(['Process', observed.process_status.running ? `running (${observed.process_status.count ?? '—'})` : 'not running']);
    if (observed.port_listener_status?.listening != null) rows.push(['Port listener', observed.port_listener_status.listening ? 'listening' : 'not listening']);
    if (observed.tcp_check?.reachable != null) rows.push(['TCP', observed.tcp_check.reachable ? 'reachable' : 'unreachable']);
    if (observed.config_validate?.valid != null) rows.push(['Config', observed.config_validate.valid ? 'valid' : 'invalid']);
    return rows.map(([label, value]) => `<div class="operator-summary-fact"><span>${esc(label)}</span><strong>${esc(value)}</strong></div>`).join('') || '<p class="operator-summary-muted">Evidence ساختاریافته کافی برای وضعیت دقیق سرویس/Process/Port موجود نیست.</p>';
  }

  function evidenceRows(items = []) {
    return items.slice(0, 8).map(item => `<div class="operator-summary-evidence"><div><b>${esc(item.diagnostic || item.type || item.source || 'evidence')}</b><span>${esc(item.source || 'unknown')}</span></div><p>${esc(item.summary || 'Evidence ثبت شده')}</p><code>${esc(item.evidence_id || item.reference || 'بدون شناسه')}</code></div>`).join('') || '<p class="operator-summary-muted">Evidence کلیدی قابل نمایش ثبت نشده است.</p>';
  }

  function actionText(action) {
    if (!action) return 'پیشنهاد عملیاتی ساختاریافته ثبت نشده است.';
    const pieces = [action.action, action.tool ? `از طریق ${action.tool}` : '', action.target ? `روی ${action.target}` : ''].filter(Boolean);
    return action.text_fa || pieces.join(' ') || 'پیشنهاد عملیاتی ساختاریافته ثبت نشده است.';
  }

  function controlRows(summary) {
    const decision = summary.decision || {};
    const approval = summary.approval || {};
    return `<div class="operator-summary-control-grid">
      <div><span>Risk</span><strong>${esc(summary.risk_level || 'unknown')}</strong></div>
      <div><span>Decision</span><strong>${esc(decision.action || decision.decision || '—')}</strong></div>
      <div><span>Approval</span><strong>${esc(summary.approval_status || 'not_requested')}</strong></div>
      <div><span>Approver</span><strong>${esc(summary.approver || '—')}</strong></div>
      <div><span>Binding</span><strong>${approval.binding_complete ? 'complete' : 'not complete / not recorded'}</strong></div>
    </div>`;
  }

  function executionText(summary) {
    const execution = summary.execution;
    if (!execution) return 'عملیاتی اجرا نشده است.';
    const parts = [execution.tool, execution.action, execution.target].filter(Boolean).join(' → ');
    const result = execution.reason || execution.error || (execution.result ? JSON.stringify(execution.result) : '');
    return `${parts || 'Execution ثبت شده'}${result ? ` · ${result}` : ''}`;
  }

  function verificationText(summary) {
    const verification = summary.verification;
    if (!verification) return 'Verification هنوز ثبت نشده است.';
    const details = [];
    if (verification.message) details.push(verification.message);
    if (verification.confidence != null) details.push(`confidence=${pct(verification.confidence)}`);
    if (verification.evidence_refs?.length) details.push(`evidence=${verification.evidence_refs.length}`);
    return details.join(' · ') || `status=${verification.status || summary.verification_status}`;
  }

  function operatorSummaryCard(summary) {
    const human = summary.human_action_indicator || {};
    return `<section class="operator-summary-card" dir="rtl" lang="fa">
      <div class="operator-summary-head">
        <div><span class="section-kicker">Decision support · durable evidence</span><h3>خلاصه فارسی رخداد</h3></div>
        <div class="operator-summary-badges">${causeBadge(summary)}${approvalBadge(summary.approval_status)}${executionBadge(summary.execution_status)}${verificationBadge(summary.verification_status)}</div>
      </div>
      <p class="operator-summary-lead">${esc(summary.summary_fa || 'خلاصه فارسی از داده‌های فعلی قابل تولید نیست.')}</p>
      <div class="operator-summary-sections">
        <article><h4>چه چیزی مشاهده شد؟</h4><div class="operator-summary-facts">${observedStateRows(summary.observed_state)}</div></article>
        <article><h4>علت محتمل ${causeBadge(summary)}</h4><p>${esc(summary.likely_cause || 'نامشخص')}</p></article>
        <article><h4>نشانه‌های اقدام انسانی ${summaryBadge(human.status_fa || 'نامشخص', lower(human.status || 'unknown'))}</h4><p>${esc(human.text_fa || 'شواهد کافی موجود نیست.')}</p></article>
        <article><h4>پیشنهاد AIOps</h4><p>${esc(actionText(summary.recommended_action))}</p></article>
        <article><h4>وضعیت کنترل ${approvalBadge(summary.approval_status)}</h4>${controlRows(summary)}</article>
        <article><h4>اجرای عملیات ${executionBadge(summary.execution_status)}</h4><p>${esc(executionText(summary))}</p></article>
        <article><h4>Verification ${verificationBadge(summary.verification_status)}</h4><p>${esc(verificationText(summary))}</p></article>
        <article><h4>Operational Memory ${memoryBadge(summary.memory_status)}</h4><p>${summary.memory_status === 'persisted' ? 'نتیجه تأییدشده در Operational Memory ثبت شده است.' : summary.memory_status === 'not_persisted' ? 'Write-back ثبت شده اما نتیجه persist نشده است.' : 'Write-back یا Memory Entry برای این چرخه ثبت نشده است.'}</p></article>
        <article class="operator-summary-wide"><h4>شواهد کلیدی</h4><div class="operator-summary-evidence-list">${evidenceRows(summary.key_evidence || [])}</div></article>
        <article class="operator-summary-wide next-step"><h4>پیشنهاد به اپراتور</h4><p>${esc(summary.operator_next_step || 'Evidence و Governance state را بازبینی کنید.')}</p></article>
      </div>
      <div class="operator-summary-policy">این Summary فقط Decision Support است؛ Approval یا Execution Authority ایجاد نمی‌کند و از Evidence جدیدی خارج از داده‌های Incident استفاده نمی‌کند.</div>
    </section>`;
  }

  function injectOperatorSummary() {
    const detail = document.querySelector('#detail');
    const head = detail?.querySelector('.detail-head');
    if (!detail || !head) return;
    detail.querySelector('.operator-summary-card')?.remove();
    if (S.operatorSummaryPending) {
      head.insertAdjacentHTML('afterend', '<section class="operator-summary-card loading" dir="rtl" lang="fa"><h3>خلاصه فارسی رخداد</h3><p>در حال خواندن وضعیت پایدار فعلی Incident…</p></section>');
      return;
    }
    if (S.operatorSummaryError) {
      head.insertAdjacentHTML('afterend', `<section class="operator-summary-card unavailable" dir="rtl" lang="fa"><h3>خلاصه فارسی رخداد</h3><p>${esc(S.operatorSummaryError)}</p><small>داده‌های ساختاریافته Incident در بخش‌های زیر همچنان قابل مشاهده هستند.</small></section>`);
      return;
    }
    if (S.operatorSummary) head.insertAdjacentHTML('afterend', operatorSummaryCard(S.operatorSummary));
  }

  async function refreshIncidentDecision() {
    const id = S.selected;
    if (!id) return;
    await selectIncident(id);
    renderDetail('decision');
  }

  window.approveCurrentApproval = async function approveCurrentApproval() {
    const approval = S.detail?.lifecycle?.approval;
    if (!approval?.approval_id || lower(approval.status) !== 'pending') return;
    const risk = lower(approval.risk_level);
    const first = window.confirm(`Approve governed action \"${approval.action}\"?\n\nThis grants authorization but does NOT execute it yet.`);
    if (!first) return;
    if (risk === 'high' && !window.confirm('HIGH-RISK approval: confirm that you reviewed target, tool, evidence, runbook and blast radius.')) return;
    try {
      await api(`/api/v1/approvals/${encodeURIComponent(approval.approval_id)}/approve`, {method: 'POST'});
      toast('Approval granted. Workflow remains paused until Resume & Execute.');
      await refreshIncidentDecision();
    } catch (error) {
      showError(error.message);
      toast('Approval failed');
    }
  };

  window.rejectCurrentApproval = async function rejectCurrentApproval() {
    const approval = S.detail?.lifecycle?.approval;
    if (!approval?.approval_id || lower(approval.status) !== 'pending') return;
    const input = document.querySelector('#rejectReason');
    const reason = String(input?.value || '').trim();
    if (!reason) {
      toast('Rejection reason is required');
      input?.focus();
      return;
    }
    if (!window.confirm(`Reject governed action \"${approval.action}\"?`)) return;
    try {
      await api(`/api/v1/approvals/${encodeURIComponent(approval.approval_id)}/reject`, {
        method: 'POST',
        headers: {'Content-Type': 'application/json'},
        body: JSON.stringify({reason})
      });
      toast('Approval rejected and audited');
      await refreshIncidentDecision();
    } catch (error) {
      showError(error.message);
      toast('Rejection failed');
    }
  };

  window.resumeCurrentWorkflow = async function resumeCurrentWorkflow() {
    const lifecycle = S.detail?.lifecycle || {};
    const approval = lifecycle.approval;
    const id = S.selected;
    if (!id || !approval?.approval_id || lower(approval.status) !== 'approved') return;
    const meta = approval.metadata || {};
    const binding = meta.binding_complete === true || lower(meta.binding_complete) === 'true';
    if (!binding) {
      toast('Execution binding is incomplete');
      return;
    }
    const summary = [meta.tool_name, approval.action, meta.target].filter(Boolean).join(' → ');
    if (!window.confirm(`Resume this approved workflow and execute the bound action?\n\n${summary}\n\nThe approval will be consumed exactly once when execution begins.`)) return;
    if (lower(approval.risk_level) === 'high' && !window.confirm('HIGH-RISK execution: confirm final operator intent to consume the approval and execute now.')) return;

    const button = document.querySelector('#resumeExecutionBtn');
    if (button) {
      button.disabled = true;
      button.textContent = 'Executing…';
    }
    showError();
    try {
      const result = await api(`/api/v1/workflow/e2e/${encodeURIComponent(id)}/resume`, {method: 'POST'});
      const verification = result.verification_result?.status || 'not recorded';
      toast(`Execution completed · verification ${verification}`);
      await loadAll();
      await refreshIncidentDecision();
    } catch (error) {
      showError(`Resume/execute failed: ${error.message}`);
      toast('Execution did not complete');
      await refreshIncidentDecision();
    }
  };

  selectIncident = async function selectIncidentWithOperatorSummary(id) {
    S.operatorSummary = null;
    S.operatorSummaryError = null;
    S.operatorSummaryPending = true;
    S.detail = null;
    const summaryRequest = api(`/api/v1/incidents/${encodeURIComponent(id)}/operator-summary`)
      .then(value => ({value, error: null}))
      .catch(error => ({value: null, error: error.message}));
    await baseSelectIncident(id);
    if (S.selected !== id) return;
    const result = await summaryRequest;
    S.operatorSummary = result.value;
    S.operatorSummaryError = result.error;
    S.operatorSummaryPending = false;
    if (S.detail?.context?.incident_id === id) renderDetail('overview');
  };

  renderDetail = function enhancedRenderDetail(tab = 'overview') {
    baseRenderDetail(tab);
    injectOperatorSummary();
    if (tab !== 'decision') return;
    const pane = document.querySelector('#detailPane');
    if (!pane) return;
    const existing = pane.innerHTML;
    pane.innerHTML = `${approvalPanel()}${existing}`;
  };

  loadAll = async function loadAllWithCurrentIncidentSummary() {
    const selectedBeforeRefresh = S.selected;
    await baseLoadAll();
    if (selectedBeforeRefresh && S.selected === selectedBeforeRefresh && S.view === 'incidents') {
      await selectIncident(selectedBeforeRefresh);
    }
  };

  window.selectIncident = selectIncident;
  window.renderDetail = renderDetail;
  window.loadAll = loadAll;
})();

(() => {
  const baseRenderDetailForAgentAnalysis = window.renderDetail;
  const baseLoadAgentsForCompatibility = typeof loadAgents === 'function' ? loadAgents : window.loadAgents;

  const list = value => Array.isArray(value) ? value : value == null ? [] : [value];
  const uniqueText = values => [...new Set(values.flatMap(list).map(value => String(value ?? '').trim()).filter(Boolean))];

  function safeJson(value, limit = 18000) {
    try {
      const raw = JSON.stringify(value ?? {}, null, 2);
      return raw.length > limit ? `${raw.slice(0, limit)}\n… dashboard preview truncated; full payload remains durable in the API.` : raw;
    } catch {
      return '{"error":"unserializable dashboard payload"}';
    }
  }

  function detailsFor(agent) {
    return agent?.analysis_details && typeof agent.analysis_details === 'object' && !Array.isArray(agent.analysis_details)
      ? agent.analysis_details
      : {};
  }

  function analyzerKeys(details) {
    return Object.keys(details)
      .filter(key => key.endsWith('_analysis') && !['deterministic_analysis', 'shared_deterministic_analysis'].includes(key))
      .slice(0, 8);
  }

  function candidateCount(details) {
    return Object.entries(details).reduce((total, [key, value]) => {
      if (!Array.isArray(value)) return total;
      return /(candidate|hypoth|contributor|cause)/i.test(key) ? total + value.length : total;
    }, 0);
  }

  function agentAnalysisCard(agent) {
    const details = detailsFor(agent);
    const telemetry = details.analyzer_telemetry && typeof details.analyzer_telemetry === 'object'
      ? details.analyzer_telemetry
      : {};
    const analyzers = analyzerKeys(details);
    const missing = uniqueText([
      ...(agent.missing_evidence || []),
      ...(details.missing_evidence || []),
      ...(details.evidence_gaps || []),
    ]).slice(0, 10);
    const stale = uniqueText(details.stale_evidence_ids || []).slice(0, 10);
    const nextBest = uniqueText(details.next_best_evidence || []).slice(0, 8);
    const handoffs = uniqueText([
      ...(agent.handoff_agents || []),
      ...(details.handoff_agents || []),
    ]).slice(0, 8);
    const candidates = candidateCount(details);
    const executionBoundary = details.execution_boundary || details.policy?.execution_boundary || 'analysis_only';
    const analyzerDuration = telemetry.duration_ms != null ? `${Number(telemetry.duration_ms).toFixed(1)} ms` : '—';

    return `<article class="agent-card">
      <div style="display:flex;justify-content:space-between;gap:12px;align-items:flex-start">
        <div><span class="section-kicker">Specialist analysis</span><h4>${esc(agent.agent_name || agent.agent || 'agent')}</h4></div>
        ${pill(agent.health_status || agent.severity || 'analyzed')}
      </div>
      <p>${esc(agent.statement || agent.finding_type || 'Structured specialist analysis')}</p>
      <div class="fact-grid">
        <div class="fact"><label>Confidence</label><strong>${pct(agent.confidence)}</strong></div>
        <div class="fact"><label>Evidence coverage</label><strong>${pct(agent.evidence_coverage)}</strong></div>
        <div class="fact"><label>Candidates</label><strong>${candidates}</strong></div>
        <div class="fact"><label>Analyzer time</label><strong>${esc(analyzerDuration)}</strong></div>
        <div class="fact"><label>Missing evidence</label><strong>${missing.length}</strong></div>
        <div class="fact"><label>Stale evidence</label><strong>${stale.length}</strong></div>
      </div>
      <div class="tags">${analyzers.map(key => `<span>${esc(key.replace(/_analysis$/, ''))}</span>`).join('')}${handoffs.map(name => `<span>handoff:${esc(name)}</span>`).join('')}<span>${esc(executionBoundary)}</span></div>
      ${missing.length ? `<div class="insight-card"><h4>Missing evidence</h4><p>${esc(missing.join(' · '))}</p></div>` : ''}
      ${nextBest.length ? `<div class="insight-card"><h4>Next best evidence</h4><p>${esc(nextBest.join(' · '))}</p></div>` : ''}
      ${stale.length ? `<div class="insight-card"><h4>Stale evidence excluded / penalized</h4><p>${esc(stale.join(' · '))}</p></div>` : ''}
      <details class="insight-card"><summary>Full structured analysis</summary><div class="json">${esc(safeJson(agent))}</div></details>
    </article>`;
  }

  renderDetail = function renderDetailWithAgentAnalysis(tab = 'overview') {
    baseRenderDetailForAgentAnalysis(tab);
    if (tab !== 'agents') return;
    const pane = document.querySelector('#detailPane');
    if (!pane) return;
    const lifecycle = S.detail?.lifecycle || {};
    const agents = Array.isArray(lifecycle.agents) ? lifecycle.agents : [];
    const coordination = lifecycle.coordination || {};
    const routing = lifecycle.routing || {};
    pane.innerHTML = `<div class="insight-card"><h4>Specialist routing & coordination</h4><p>${esc(coordination.summary || coordination.statement || 'Deterministic routing, peer coordination and evidence requests are preserved below.')}</p><div class="json">${esc(safeJson({routing, coordination}, 10000))}</div></div>`
      + (agents.map(agentAnalysisCard).join('') || '<div class="empty-state">No specialist findings recorded.</div>');
  };
  window.renderDetail = renderDetail;

  if (typeof baseLoadAgentsForCompatibility === 'function') {
    loadAgents = async function loadAgentsWithReliabilityContract() {
      await baseLoadAgentsForCompatibility();
      const metricByAgent = {};
      (S.agentMetrics || []).forEach(metric => {
        metricByAgent[metric.agent_name || metric.agent] = metric;
      });
      document.querySelectorAll('#agentsGrid .agent-manifest').forEach((card, index) => {
        const agent = (S.agents || [])[index] || {};
        const metric = metricByAgent[agent.name] || {};
        const requirements = uniqueText(agent.evidence_requirements || []).slice(0, 6);
        const handoffs = uniqueText(agent.handoff_targets || []).slice(0, 6);
        card.insertAdjacentHTML('beforeend', `<div class="tags"><span>${esc(agent.production_status || 'analysis_only')}</span>${requirements.map(item => `<span>evidence:${esc(item)}</span>`).join('')}${handoffs.map(item => `<span>handoff:${esc(item)}</span>`).join('')}</div><div class="mini-metrics"><div><label>Evidence coverage</label><strong>${pct(metric.average_evidence_coverage || 0)}</strong></div><div><label>Failures</label><strong>${metric.failures ?? 0}</strong></div><div><label>Handoffs</label><strong>${metric.handoffs ?? 0}</strong></div><div><label>Conflicts</label><strong>${metric.conflicts ?? 0}</strong></div></div>`);
      });
    };
    window.loadAgents = loadAgents;
  }
})();