const S={key:localStorage.getItem('aiops_api_key')||'',summary:null,incidents:[],services:[],health:null,agents:[],agentMetrics:[],selected:null,detail:null,view:'overview'};
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const lower=v=>String(v??'').toLowerCase();
const fmtDate=v=>v?new Date(v).toLocaleString():'—';
const fmtShortDate=v=>v?new Date(v).toLocaleString([], {month:'short',day:'2-digit',hour:'2-digit',minute:'2-digit'}):'—';
const pct=v=>`${Math.round((Number(v)||0)*100)}%`;
const isOpen=i=>!['closed','resolved'].includes(lower(i.status));
function pill(v=''){const s=lower(v);let c='';if(/critical|failed|failure|rejected|unhealthy|error/.test(s))c='red';else if(/success|approved|resolved|healthy|ready|verified|completed/.test(s))c='green';else if(/pending|high|warning|degraded/.test(s))c='amber';else if(/analyz|running|medium/.test(s))c='violet';return `<span class="pill ${c}">${esc(v||'—')}</span>`}
function headers(){const h={'Accept':'application/json'};if(S.key)h['X-API-Key']=S.key;return h}
async function api(path,opts={}){const r=await fetch(path,{...opts,headers:{...headers(),...(opts.headers||{})}});if(!r.ok){let d;try{d=await r.json()}catch{}throw new Error(`${r.status} ${d?.detail||r.statusText}`)}return r.json()}
function showError(msg=''){const el=$('#error');el.textContent=msg;el.classList.toggle('hidden',!msg)}
function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2400)}
function saveKey(){S.key=$('#apiKey').value.trim();localStorage.setItem('aiops_api_key',S.key);toast('API identity updated');loadAll()}
function syncGlobalSearch(v){if($('#incidentSearch'))$('#incidentSearch').value=v;if($('#serviceSearch'))$('#serviceSearch').value=v;renderIncidents();renderServices()}
function setView(v){S.view=v;$$('.view').forEach(x=>x.classList.toggle('active',x.dataset.view===v));$$('.nav button').forEach(x=>x.classList.toggle('active',x.dataset.view===v));const titles={overview:['Command Center','Prioritized live operational state across incidents, services and governed automation.'],incidents:['Incident Workbench','Investigate evidence, RCA, governance and recovery in one durable incident view.'],services:['Service Health','Service-centric operational impact derived from live incident and governance state.'],agents:['Agents & RCA','Analysis-only specialist agents, capabilities and runtime quality signals.'],mcp:['MCP Fabric','Health of governed external operational-tool connectivity.'],audit:['Audit & Governance','Durable decision, approval, execution and verification history.']};$('#pageTitle').textContent=titles[v][0];$('#pageSub').textContent=titles[v][1];if(v==='agents')loadAgents();if(v==='services')renderServices();if(v==='mcp')renderMcp();if(v==='audit')renderAudit()}
function serviceState(s){if(Number(s.critical_active)>0||Number(s.failed_verifications)>0)return 'critical';if(Number(s.high_active)>0||Number(s.incidents_active)>0||Number(s.approvals_pending)>0)return 'degraded';return 'healthy'}
function attentionReason(i){const reasons=[];if(lower(i.severity)==='critical')reasons.push('critical severity');else if(lower(i.severity)==='high')reasons.push('high severity');if(lower(i.approval_status)==='pending')reasons.push('approval pending');if(/failed|failure/.test(lower(i.verification_status)))reasons.push('verification failed');if(Number(i.confidence||0)>0&&Number(i.confidence)<.5)reasons.push('low confidence');return reasons}
function attentionRank(i){let n=0;if(lower(i.severity)==='critical')n+=100;else if(lower(i.severity)==='high')n+=60;else if(lower(i.severity)==='medium')n+=20;if(lower(i.approval_status)==='pending')n+=30;if(/failed|failure/.test(lower(i.verification_status)))n+=50;if(Number(i.confidence||0)>0&&Number(i.confidence)<.5)n+=15;return n}
function attentionLevel(score){return score>=100?'P0':score>=60?'P1':'P2'}
function renderOverview(){const x=S.summary||{};$('#kActive').textContent=x.incidents_active??'—';$('#kCritical').textContent=x.incidents_critical??'—';$('#kPending').textContent=x.approvals_pending??'—';$('#kSuccess').textContent=x.successful_remediations??'—';$('#kRate').textContent=pct(x.automation_success_rate);$('#kConfidence').textContent=pct(x.mean_confidence);const live=x.data_status==='live';$('#liveDot').classList.toggle('ok',live);$('#platformState').textContent=live?'Live':'Unavailable';$('#platformState').classList.toggle('live',live);$('#lastUpdated').textContent=live?new Date().toLocaleTimeString():'—';
const attention=S.incidents.filter(i=>isOpen(i)&&attentionReason(i).length).sort((a,b)=>attentionRank(b)-attentionRank(a));const atRisk=S.services.filter(s=>serviceState(s)!=='healthy');$('#attentionCount').textContent=attention.length;$('#serviceRiskCount').textContent=atRisk.length;$('#attentionBadge').textContent=`${attention.length} live`;$('#attentionQueue').innerHTML=attention.slice(0,7).map(i=>{const score=attentionRank(i),level=attentionLevel(score),critical=level==='P0'?'critical':'';return `<div class="attention-item" onclick="openIncident('${esc(i.id)}')"><i class="attention-marker ${critical}"></i><div><div class="attention-title">${esc(i.service||'Unknown service')} · ${esc(i.summary||'Incident')}</div><div class="attention-meta">${esc(attentionReason(i).join(' · '))} · ${fmtShortDate(i.created_at)}</div></div><div class="attention-score"><strong>${level}</strong><small>${esc(i.severity||'')}</small></div></div>`}).join('')||'<div class="empty-state">No active incident currently requires elevated operator attention.</div>';
$('#servicePreview').innerHTML=S.services.slice(0,6).map(s=>{const state=serviceState(s);return `<div class="service-row"><div><div class="service-name">${esc(s.service)}</div><div class="service-summary">${esc(s.latest_summary||'No recent incident summary')}</div></div><div><div class="health-bar"><i class="${state}" style="width:${state==='healthy'?100:state==='degraded'?58:28}%"></i></div></div><div class="service-counts"><b>${s.incidents_active}</b>active · ${esc(state)}</div></div>`}).join('')||'<div class="empty-state">No durable service incident history is available.</div>';
renderSeverity();renderAuditPreview()}
function renderSeverity(){const sev={critical:0,high:0,medium:0,low:0};S.incidents.filter(isOpen).forEach(i=>{const s=lower(i.severity);if(sev[s]!=null)sev[s]++});const total=Object.values(sev).reduce((a,b)=>a+b,0);const colors={critical:'var(--red)',high:'var(--amber)',medium:'var(--blue)',low:'var(--green)'};$('#severityBreakdown').innerHTML=total?Object.entries(sev).map(([k,n])=>`<div class="severity-row"><span>${k}</span><div class="severity-bar"><i style="width:${n/total*100}%;background:${colors[k]}"></i></div><b>${n}</b></div>`).join(''):'<div class="empty-state">No active incidents.</div>'}
function renderAuditPreview(){const audit=S.summary?.recent_audit||[];$('#auditPreview').innerHTML=audit.slice(0,3).map(a=>timelineItem(a)).join('')||'<div class="empty-state">No audit events recorded.</div>'}
function timelineItem(a){return `<div class="timeline-item"><div class="timeline-title">${esc(a.event_type||'event')}</div><div class="timeline-meta">${fmtShortDate(a.created_at)} · ${esc(String(a.incident_id||'no incident').slice(0,8))}</div><div class="timeline-body">${esc(a.action||a.status||'Governance event recorded')}</div></div>`}
function renderHealth(){const h=S.health?.components||{},ext=h.external||{};const defs=[['Database',h.database?.status==='healthy',h.database?.pgvector?'PostgreSQL + pgvector':'PostgreSQL'],['Zabbix MCP',ext.zabbix_mcp?.healthy,'Monitoring evidence'],['Elastic MCP',ext.elasticsearch_mcp?.healthy,'Agent Builder evidence'],['Prometheus MCP',ext.prometheus_mcp?.healthy,'Metrics evidence']];$('#components').innerHTML=defs.map(([name,ok,meta])=>`<div class="component"><div class="component-top"><span class="component-name">${name}</span><span class="dot ${ok?'green':''}" style="${ok?'':'background:var(--red)'}"></span></div><div class="component-state ${ok?'ok':'bad'}">${ok?'Healthy':'Unavailable'}</div><small>${meta}</small></div>`).join('')}
function renderIncidents(){const q=lower($('#incidentSearch')?.value),sev=$('#severityFilter')?.value||'',status=$('#statusFilter')?.value||'';const rows=S.incidents.filter(i=>(!q||lower([i.id,i.service,i.summary].join(' ')).includes(q))&&(!sev||lower(i.severity)===sev)&&(!status||lower(i.status)===status));if($('#incidentCount'))$('#incidentCount').textContent=`${rows.length} incidents`;if(!$('#incidentRows'))return;$('#incidentRows').innerHTML=rows.map(i=>`<tr class="${S.selected===i.id?'selected':''}" onclick="selectIncident('${esc(i.id)}')"><td><div class="incident-main">${esc(String(i.id).slice(0,8))}</div><div class="incident-sub">${esc(i.summary||'')}</div></td><td>${esc(i.service||'—')}</td><td>${pill(i.severity)}</td><td>${pill(i.status)}</td><td>${pct(i.confidence)}</td><td>${pill(i.risk_level||'—')}</td><td>${pill(i.approval_status||'—')}</td><td>${pill(i.verification_status||'—')}</td><td>${fmtShortDate(i.created_at)}</td></tr>`).join('')||'<tr><td colspan="9"><div class="empty-state">No incidents match the current filters.</div></td></tr>'}
function renderServices(){if(!$('#serviceGrid'))return;const q=lower($('#serviceSearch')?.value),risk=$('#serviceRiskFilter')?.value||'';const rows=S.services.filter(s=>(!q||lower([s.service,s.latest_summary].join(' ')).includes(q))&&(!risk||serviceState(s)===risk));$('#serviceCount').textContent=`${rows.length} services`;$('#serviceGrid').innerHTML=rows.map(s=>{const state=serviceState(s);return `<article class="panel service-card"><div class="service-card-top"><div><span class="section-kicker">Service</span><h3>${esc(s.service)}</h3></div>${pill(state)}</div><p>${esc(s.latest_summary||'No incident summary available.')}</p><div class="service-metrics"><div class="service-metric"><label>Active</label><strong>${s.incidents_active}</strong></div><div class="service-metric"><label>Critical / High</label><strong>${s.critical_active} / ${s.high_active}</strong></div><div class="service-metric"><label>Confidence</label><strong>${pct(s.mean_active_confidence)}</strong></div></div><div class="service-footer"><span>${s.approvals_pending} pending approvals · ${s.failed_verifications} failed verifications</span><span>${fmtShortDate(s.last_incident_at)}</span></div></article>`}).join('')||'<div class="panel empty-state">No services match the current filter.</div>'}
function openIncident(id){setView('incidents');selectIncident(id)}
async function selectIncident(id){S.selected=id;renderIncidents();$('#detail').innerHTML='<div class="empty-state tall">Loading durable incident state…</div>';try{const [context,evidence,lifecycle,verification]=await Promise.all([api(`/api/v1/incidents/${id}/context`),api(`/api/v1/incidents/${id}/evidence?limit=100`),api(`/api/v1/incidents/${id}/lifecycle`),api(`/api/v1/incidents/${id}/verification`)]);S.detail={context,evidence,lifecycle,verification};renderDetail('overview')}catch(e){$('#detail').innerHTML=`<div class="empty-state tall">${esc(e.message)}</div>`}}
function workflowStages(l){const order=['context','triage','agents','rca','decision','execution'];const cur=lower(l.current_node);let reached=true;return order.map(n=>{let c='';if(reached)c='done';if(cur.includes(n)||(n==='agents'&&/specialist|analysis/.test(cur))){c='current';reached=false}else if(!reached)c='';return `<div class="stage ${c}">${n}</div>`}).join('')}
function confidenceBlock(label,value){const n=Math.max(0,Math.min(1,Number(value)||0));return `<div class="insight-card"><h4>${esc(label)}</h4><div class="confidence-line"><div class="confidence-meter"><i style="width:${n*100}%"></i></div><b>${pct(n)}</b></div></div>`}
function renderDetail(tab='overview'){if(!S.detail)return;const {context:c,evidence:e,lifecycle:l,verification:v}=S.detail;const incident=S.incidents.find(x=>x.id===S.selected)||{};$('#detail').innerHTML=`<div class="detail-head"><div class="detail-title-row"><div><div class="detail-title">${esc(c.service||incident.service||'Incident')}</div><div class="detail-id">${esc(c.incident_id||S.selected)}</div></div>${pill(c.severity||incident.severity)}</div><div class="detail-summary">${esc(c.summary||incident.summary||'No incident summary')}</div><div class="fact-grid"><div class="fact"><label>Status</label><strong>${esc(c.status||incident.status||'—')}</strong></div><div class="fact"><label>Current node</label><strong>${esc(l.current_node||'—')}</strong></div><div class="fact"><label>Risk</label><strong>${esc(incident.risk_level||'—')}</strong></div><div class="fact"><label>Evidence rounds</label><strong>${esc(l.evidence_rounds??0)}</strong></div></div></div><div class="tabs">${['overview','evidence','agents','decision','verification','audit'].map(t=>`<button class="${t===tab?'active':''}" onclick="renderDetail('${t}')">${t}</button>`).join('')}</div><div id="detailPane" class="detail-pane"></div>`;
const pane=$('#detailPane');if(tab==='overview'){const coord=l.coordination||{},evaln=l.evaluation||{};pane.innerHTML=`<div class="workflow">${workflowStages(l)}</div>${confidenceBlock('Incident confidence',incident.confidence)}<div class="insight-card"><h4>RCA / coordination</h4><p>${esc(coord.summary||coord.statement||l.terminal_reason||'Structured coordination state is available below.')}</p><div class="json">${esc(JSON.stringify({triage:l.triage,coordination:coord,evaluation:evaln},null,2))}</div></div><div class="insight-card"><h4>Governed control state</h4><p>Decision ${esc(l.decision?.decision||incident.decision||'pending')} · Approval ${esc(l.approval?.status||incident.approval_status||'not requested')} · Execution ${esc(l.execution?.status||'not recorded')}</p></div>`}
if(tab==='evidence')pane.innerHTML=(e.items||[]).map(x=>`<div class="evidence-card"><h4>${esc(x.source||'evidence')} · ${esc(x.type||'record')}</h4><p>${esc(x.reference||x.query||'Durable production evidence')}</p><div class="json">${esc(JSON.stringify(x.raw_data||{},null,2))}</div></div>`).join('')||'<div class="empty-state">No evidence recorded.</div>';
if(tab==='agents')pane.innerHTML=(l.agents||[]).map(a=>`<div class="agent-card"><h4>${esc(a.agent_name||a.agent||'agent')}</h4><p>${esc(a.statement||a.finding_type||'Structured specialist analysis')}</p><div class="confidence-line"><div class="confidence-meter"><i style="width:${Math.max(0,Math.min(1,Number(a.confidence)||0))*100}%"></i></div><b>${pct(a.confidence)}</b></div></div>`).join('')||'<div class="empty-state">No specialist findings recorded.</div>';
if(tab==='decision')pane.innerHTML=`<div class="insight-card"><h4>Decision</h4><div class="json">${esc(JSON.stringify(l.decision||{},null,2))}</div></div><div class="insight-card"><h4>Approval</h4><div class="json">${esc(JSON.stringify(l.approval||{},null,2))}</div></div><div class="insight-card"><h4>Execution</h4><div class="json">${esc(JSON.stringify(l.execution||{},null,2))}</div></div>`;
if(tab==='verification')pane.innerHTML=`<div class="insight-card"><h4>Independent verification</h4><p>${esc(v.status||incident.verification_status||'No verification state')}</p></div>${(v.items||[]).map(x=>`<div class="insight-card"><h4>${esc(x.event_type||'verification')}</h4><div class="json">${esc(JSON.stringify(x,null,2))}</div></div>`).join('')}`;
if(tab==='audit')pane.innerHTML=(l.audit||[]).map(a=>timelineItem(a)).join('')||'<div class="empty-state">No incident audit events.</div>'}
async function loadAgents(){try{const [c,m]=await Promise.all([api('/api/v1/agents/catalog'),api('/api/v1/agents/metrics')]);S.agents=c.items||[];S.agentMetrics=m.items||[];const metrics={};S.agentMetrics.forEach(x=>metrics[x.agent_name||x.agent]=x);$('#agentsGrid').innerHTML=S.agents.map(a=>{const met=metrics[a.name]||{};return `<article class="panel agent-manifest"><div style="display:flex;justify-content:space-between">${pill(a.enabled?'enabled':'disabled')}<span class="muted" style="font-size:7px">${esc(a.version||'')}</span></div><h3>${esc(a.name)}</h3><p>${esc(a.description||a.responsibility||'Analysis-only specialist')}</p><div class="tags">${(a.capabilities||a.read_capabilities||[]).slice(0,6).map(x=>`<span>${esc(x)}</span>`).join('')}</div><div class="mini-metrics"><div><label>Invocations</label><strong>${met.invocations??0}</strong></div><div><label>Avg confidence</label><strong>${pct(met.average_confidence||0)}</strong></div></div></article>`}).join('')||'<div class="panel empty-state">No agents available.</div>'}catch(e){showError(e.message)}}
function renderMcp(){if(!$('#mcpGrid'))return;const ext=S.health?.components?.external||{};const defs=[['Zabbix MCP','zabbix_mcp','Monitoring alerts, problems and host context'],['Elastic Agent Builder MCP','elasticsearch_mcp','Logs and governed ES|QL evidence'],['Prometheus MCP','prometheus_mcp','Metrics, series and alert evidence']];$('#mcpGrid').innerHTML=defs.map(([name,key,desc])=>{const x=ext[key]||{};return `<article class="panel mcp-card"><div class="mcp-icon">◇</div><h3>${name}</h3><p>${desc}</p><div class="mcp-status"><span>Connection</span>${pill(x.healthy?'healthy':'unavailable')}</div></article>`}).join('')}
function renderAudit(){if(!$('#auditList'))return;const a=S.summary?.recent_audit||[];$('#auditList').innerHTML=a.map(timelineItem).join('')||'<div class="empty-state">No audit events recorded.</div>'}
async function loadAll(){showError();$('#apiKey').value=S.key;try{const [summary,incidents,services,health]=await Promise.all([api('/api/v1/dashboard/summary'),api('/api/v1/dashboard/incidents?limit=100'),api('/api/v1/dashboard/services?limit=100'),api('/api/v1/health')]);S.summary=summary;S.incidents=incidents.items||[];S.services=services.items||[];S.health=health;renderOverview();renderHealth();renderIncidents();renderServices();renderMcp();renderAudit();if(!S.selected&&S.incidents[0]&&S.view==='incidents')selectIncident(S.incidents[0].id)}catch(e){showError(`Live dashboard unavailable: ${e.message}`);$('#liveDot').classList.remove('ok');$('#platformState').textContent='Unavailable'}}
window.saveKey=saveKey;window.setView=setView;window.syncGlobalSearch=syncGlobalSearch;window.selectIncident=selectIncident;window.openIncident=openIncident;window.renderDetail=renderDetail;window.renderIncidents=renderIncidents;window.renderServices=renderServices;window.renderMcp=renderMcp;window.renderAudit=renderAudit;window.loadAll=loadAll;window.addEventListener('DOMContentLoaded',()=>{if(S.key)$('#apiKey').value=S.key;loadAll();setInterval(loadAll,60000)});
