const S={key:localStorage.getItem('aiops_api_key')||'',summary:null,incidents:[],health:null,agents:[],agentMetrics:[],selected:null,detail:null,view:'overview'};
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fmtDate=v=>v?new Date(v).toLocaleString(): '—';
const pct=v=>`${Math.round((Number(v)||0)*100)}%`;
const pill=(v='')=>{const s=String(v).toLowerCase();let c='blue';if(/critical|failed|rejected|unhealthy|error/.test(s))c='red';else if(/success|approved|resolved|healthy|ready|verified|completed/.test(s))c='green';else if(/pending|high|warning|degraded/.test(s))c='amber';else if(/analyz|running|medium/.test(s))c='violet';return `<span class="pill ${c}">${esc(v||'—')}</span>`};
function headers(){const h={'Accept':'application/json'};if(S.key)h['X-API-Key']=S.key;return h}
async function api(path,opts={}){const r=await fetch(path,{...opts,headers:{...headers(),...(opts.headers||{})}});if(!r.ok){let d;try{d=await r.json()}catch{};throw new Error(`${r.status} ${d?.detail||r.statusText}`)}return r.json()}
function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2600)}
function error(msg=''){$('#error').textContent=msg;$('#error').classList.toggle('hidden',!msg)}
function saveKey(){S.key=$('#apiKey').value.trim();localStorage.setItem('aiops_api_key',S.key);loadAll();}
function setView(v){S.view=v;$$('.view').forEach(x=>x.classList.toggle('active',x.dataset.view===v));$$('.nav button').forEach(x=>x.classList.toggle('active',x.dataset.view===v));const titles={overview:['Operations Overview','Real-time governed AIOps control plane'],incidents:['Incident Operations','Evidence, RCA, policy, approval, execution and verification'],agents:['Agent Intelligence','Analysis-only specialist catalog and runtime telemetry'],mcp:['MCP Fabric','External operational-tool connectivity and health'],audit:['Audit & Governance','Durable operational events and control-plane history']};$('#pageTitle').textContent=titles[v][0];$('#pageSub').textContent=titles[v][1];if(v==='agents')loadAgents();if(v==='mcp')renderMcp();if(v==='audit')renderAudit();}
function renderSummary(){const x=S.summary||{};$('#kActive').textContent=x.incidents_active??'—';$('#kCritical').textContent=x.incidents_critical??'—';$('#kPending').textContent=x.approvals_pending??'—';$('#kSuccess').textContent=x.successful_remediations??'—';$('#kRate').textContent=pct(x.automation_success_rate);$('#kConfidence').textContent=pct(x.mean_confidence);$('#liveDot').classList.toggle('ok',x.data_status==='live');
const sev={critical:0,high:0,medium:0,low:0};S.incidents.forEach(i=>{const s=String(i.severity).toLowerCase();if(sev[s]!=null)sev[s]++});const total=Math.max(1,Object.values(sev).reduce((a,b)=>a+b,0));$('#severityBreakdown').innerHTML=Object.entries(sev).map(([k,n])=>`<div class="severity-row"><i class="sev-dot" style="background:${k==='critical'?'var(--red)':k==='high'?'var(--amber)':k==='medium'?'var(--blue)':'var(--green)'}"></i><span style="width:55px">${k}</span><div class="grow meter"><i style="width:${n/total*100}%;background:${k==='critical'?'var(--red)':k==='high'?'var(--amber)':k==='medium'?'var(--blue)':'var(--green)'}"></i></div><b>${n}</b></div>`).join('');
const audit=x.recent_audit||[];$('#auditPreview').innerHTML=audit.slice(0,7).map(a=>`<div class="audit-item"><b>${esc(a.event_type)}</b><div>${esc(a.action||a.status||'')} · ${fmtDate(a.created_at)}</div></div>`).join('')||'<div class="empty-state">No audit events.</div>';
const bars=S.incidents.slice(0,24).reverse();$('#incidentSpark').innerHTML=(bars.length?bars:Array.from({length:18},()=>null)).map((i,n)=>`<i style="height:${i?Math.max(12,25+(n%6)*10):8}%"></i>`).join('');}
function renderHealth(){const h=S.health?.components||{};const ext=h.external||{};const cards=[['Database',h.database?.status==='healthy',h.database?.pgvector?'PostgreSQL + pgvector':'PostgreSQL'],['Zabbix MCP',ext.zabbix_mcp?.healthy,ext.zabbix_mcp?.healthy?'Connected':'Unavailable'],['Elastic MCP',ext.elasticsearch_mcp?.healthy,ext.elasticsearch_mcp?.healthy?'Agent Builder':'Unavailable'],['Prometheus MCP',ext.prometheus_mcp?.healthy,ext.prometheus_mcp?.healthy?'Connected':'Unavailable']];$('#components').innerHTML=cards.map(([n,ok,m])=>`<div class="component"><div class="name">${n}</div><div class="state ${ok?'ok':'bad'}">${ok?'Healthy':'Unavailable'}</div><div class="meta">${esc(m)}</div></div>`).join('');}
function renderIncidents(){const q=$('#incidentSearch').value.toLowerCase(),sev=$('#severityFilter').value,status=$('#statusFilter').value;const rows=S.incidents.filter(i=>(!q||[i.id,i.service,i.summary].join(' ').toLowerCase().includes(q))&&(!sev||String(i.severity).toLowerCase()===sev)&&(!status||String(i.status).toLowerCase()===status));$('#incidentCount').textContent=rows.length;$('#incidentRows').innerHTML=rows.map(i=>`<tr class="${S.selected===i.id?'selected':''}" onclick="selectIncident('${i.id}')"><td><span class="mono">${esc(String(i.id).slice(0,8))}</span><br><span class="muted">${esc(i.summary||'')}</span></td><td>${esc(i.service||'—')}</td><td>${pill(i.severity)}</td><td>${pill(i.status)}</td><td>${pct(i.confidence)}</td><td>${pill(i.decision||'pending')}</td><td>${pill(i.approval_status||'—')}</td><td>${pill(i.verification_status||'—')}</td><td>${fmtDate(i.created_at)}</td></tr>`).join('')||'<tr><td colspan="9" class="empty-state">No incidents match the current filters.</td></tr>';}
async function selectIncident(id){S.selected=id;renderIncidents();$('#detail').innerHTML='<div class="detail-empty">Loading durable incident state…</div>';try{const [context,evidence,lifecycle,verification]=await Promise.all([api(`/api/v1/incidents/${id}/context`),api(`/api/v1/incidents/${id}/evidence?limit=100`),api(`/api/v1/incidents/${id}/lifecycle`),api(`/api/v1/incidents/${id}/verification`)]);S.detail={context,evidence,lifecycle,verification};renderDetail('overview')}catch(e){$('#detail').innerHTML=`<div class="detail-empty">${esc(e.message)}</div>`}}
function workflowStages(l){const order=['context','triage','agents','rca','decision','execution'];const cur=String(l.current_node||'').toLowerCase();let reached=true;return order.map(n=>{let c='';if(reached)c='done';if(cur.includes(n)|| (n==='agents'&&/specialist|analysis/.test(cur))){c='current';reached=false}else if(!reached)c='';return `<div class="stage ${c}">${n}</div>`}).join('')}
function renderDetail(tab='overview'){if(!S.detail)return;const {context:c,evidence:e,lifecycle:l,verification:v}=S.detail;$('#detail').innerHTML=`<div class="panel-body"><div class="incident-title"><div><h2>${esc(c.summary||'Incident')}</h2><p class="mono">${esc(c.incident_id)}</p></div>${pill(c.severity)}</div><div class="fields"><div class="field"><div class="k">Service</div><div class="v">${esc(c.service||'—')}</div></div><div class="field"><div class="k">Status</div><div class="v">${pill(c.status)}</div></div><div class="field"><div class="k">Current node</div><div class="v">${esc(l.current_node||'—')}</div></div><div class="field"><div class="k">Evidence rounds</div><div class="v">${esc(l.evidence_rounds??0)}</div></div></div><div class="tabs">${['overview','evidence','agents','decision','verification','audit'].map(t=>`<button class="${t===tab?'active':''}" onclick="renderDetail('${t}')">${t}</button>`).join('')}</div><div id="detailPane" class="detail-pane"></div></div>`;
const pane=$('#detailPane');if(tab==='overview')pane.innerHTML=`<div class="workflow">${workflowStages(l)}</div><div class="section-grid"><div><h4>RCA / Evaluation</h4><div class="json">${esc(JSON.stringify({triage:l.triage,coordination:l.coordination,evaluation:l.evaluation,terminal_reason:l.terminal_reason},null,2))}</div></div><div><h4>Control status</h4><div class="event"><b>Decision</b><small>${esc(JSON.stringify(l.decision||{}))}</small></div><div class="event"><b>Approval</b><small>${esc(JSON.stringify(l.approval||{}))}</small></div><div class="event"><b>Execution</b><small>${esc(JSON.stringify(l.execution||{}))}</small></div></div></div>`;
if(tab==='evidence')pane.innerHTML=(e.items||[]).map(x=>`<div class="evidence-card"><b>${esc(x.source)} · ${esc(x.type)}</b><small>${esc(x.reference||x.query||'')}</small><div class="json">${esc(JSON.stringify(x.raw_data||{},null,2))}</div></div>`).join('')||'<div class="empty-state">No evidence recorded.</div>';
if(tab==='agents')pane.innerHTML=`<div class="agent-grid">${(l.agents||[]).map(a=>{const sc=Number(a.confidence||0);return `<div class="agent-card"><b>${esc(a.agent_name||a.agent||'agent')}</b><div class="score ${sc>.75?'high':sc>.45?'mid':'low'}">${pct(sc)}</div><small>${esc(a.statement||a.finding_type||'Analysis recorded')}</small></div>`}).join('')}</div><div class="json" style="margin-top:8px">${esc(JSON.stringify(l.coordination||{},null,2))}</div>`;
if(tab==='decision')pane.innerHTML=`<div class="event"><b>Decision</b><div class="json">${esc(JSON.stringify(l.decision||{},null,2))}</div></div><div class="event"><b>Approval</b><div class="json">${esc(JSON.stringify(l.approval||{},null,2))}</div></div><div class="event"><b>Execution</b><div class="json">${esc(JSON.stringify(l.execution||{},null,2))}</div></div>`;
if(tab==='verification')pane.innerHTML=`<div class="event"><b>Verification state</b><small>${esc(v.status)}</small></div>${(v.items||[]).map(x=>`<div class="event"><b>${esc(x.event_type||'verification')}</b><div class="json">${esc(JSON.stringify(x,null,2))}</div></div>`).join('')||'<div class="empty-state">No verification recorded.</div>'}`;
if(tab==='audit')pane.innerHTML=(l.audit||[]).map(a=>`<div class="event"><b>${esc(a.event_type||'event')}</b><small>${fmtDate(a.created_at)} · ${esc(a.action||a.status||'')}</small></div>`).join('')||'<div class="empty-state">No audit events.</div>';}
async function loadAgents(){try{const [c,m]=await Promise.all([api('/api/v1/agents/catalog'),api('/api/v1/agents/metrics')]);S.agents=c.items||[];S.agentMetrics=m.items||[];const mm={};S.agentMetrics.forEach(x=>mm[x.agent_name||x.agent]=x);$('#agentsGrid').innerHTML=S.agents.map(a=>{const met=mm[a.name]||{};return `<div class="card agent-manifest"><div style="display:flex;justify-content:space-between">${pill(a.enabled?'enabled':'disabled')}<span class="muted">${esc(a.version||'')}</span></div><h3>${esc(a.name)}</h3><p>${esc(a.description||a.responsibility||'Analysis-only specialist')}</p><div class="tags">${(a.capabilities||a.read_capabilities||[]).slice(0,5).map(x=>`<span class="pill">${esc(x)}</span>`).join('')}</div><div class="fields"><div class="field"><div class="k">Invocations</div><div class="v">${met.invocations??0}</div></div><div class="field"><div class="k">Avg confidence</div><div class="v">${pct(met.average_confidence||0)}</div></div></div></div>`}).join('')||'<div class="empty-state">No agents available.</div>';}catch(e){error(e.message)}}
function renderMcp(){const ext=S.health?.components?.external||{};const defs=[['Zabbix MCP','zabbix_mcp','Monitoring alerts and host context'],['Elastic Agent Builder MCP','elasticsearch_mcp','Logs and ES|QL evidence'],['Prometheus MCP','prometheus_mcp','Metrics, series and alert evidence']];$('#mcpGrid').innerHTML=defs.map(([n,k,d])=>{const x=ext[k]||{};return `<div class="card mcp-card"><div class="icon">◈</div><h3>${n}</h3><p>${d}</p><div class="statusline"><span>Connection</span>${pill(x.healthy?'healthy':'unavailable')}</div></div>`}).join('');}
function renderAudit(){const a=S.summary?.recent_audit||[];$('#auditList').innerHTML=a.map(x=>`<div class="audit-item"><b>${esc(x.event_type)}</b><div>${fmtDate(x.created_at)} · incident ${esc(String(x.incident_id||'—').slice(0,8))}</div><div>${esc(x.action||x.status||'')}</div></div>`).join('')||'<div class="empty-state">No audit events.</div>';}
async function loadAll(){error();$('#apiKey').value=S.key;try{const [summary,incidents,health]=await Promise.all([api('/api/v1/dashboard/summary'),api('/api/v1/dashboard/incidents?limit=100'),api('/api/v1/health')]);S.summary=summary;S.incidents=incidents.items||[];S.health=health;renderSummary();renderHealth();renderIncidents();renderMcp();renderAudit();$('#updated').textContent=`Updated ${new Date().toLocaleTimeString()}`;if(!S.selected&&S.incidents[0])selectIncident(S.incidents[0].id)}catch(e){error(`Live dashboard unavailable: ${e.message}`);$('#liveDot').classList.remove('ok')}}
window.saveKey=saveKey;window.setView=setView;window.selectIncident=selectIncident;window.renderDetail=renderDetail;window.loadAll=loadAll;window.addEventListener('DOMContentLoaded',()=>{S.key&&($('#apiKey').value=S.key);loadAll();setInterval(loadAll,60000)});