from __future__ import annotations

from dataclasses import dataclass
from typing import Optional


@dataclass(frozen=True)
class ServiceDiagnosticAdapter:
    """Fixed, allowlisted service-specific diagnostic commands.

    These commands are owned by the platform, never generated by an LLM and
    never accept free-form shell fragments.
    """

    canonical_name: str
    aliases: tuple[str, ...]
    config_check_command: Optional[str] = None


_ADAPTERS = (
    ServiceDiagnosticAdapter(
        canonical_name="haproxy",
        aliases=("haproxy",),
        config_check_command="haproxy -c -f /etc/haproxy/haproxy.cfg",
    ),
    ServiceDiagnosticAdapter(
        canonical_name="nginx",
        aliases=("nginx",),
        config_check_command="nginx -t",
    ),
    ServiceDiagnosticAdapter(
        canonical_name="apache",
        aliases=("apache", "apache2", "httpd"),
        config_check_command=(
            "if command -v apachectl >/dev/null 2>&1; then apachectl configtest; "
            "elif command -v httpd >/dev/null 2>&1; then httpd -t; "
            "else exit 127; fi"
        ),
    ),
)


def get_service_adapter(service: str) -> Optional[ServiceDiagnosticAdapter]:
    name = str(service or "").strip().lower()
    for adapter in _ADAPTERS:
        if name == adapter.canonical_name or name in adapter.aliases:
            return adapter
    return None
